# Generated by Django 4.0.5 on 2022-07-03 04:26

from django.db import migrations, models
import home_app.models.current_incoming_event
import home_app.models.our_partners
import home_app.models.our_success_story
import home_app.models.our_volunteers
import home_app.models.trending_fundraiser
import home_app.models.what_people_say


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carousel_img', models.ImageField(upload_to='carousel_image')),
            ],
        ),
        migrations.CreateModel(
            name='current_incoming_event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_img', models.ImageField(upload_to='image_upload/event_image')),
                ('event_name', models.CharField(max_length=50)),
                ('about_event', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='our_partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_logo', models.ImageField(upload_to='image_upload/event_image')),
                ('partner_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='our_success_story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_logo', models.ImageField(upload_to='image_upload/event_image')),
                ('success_heading', models.CharField(max_length=100)),
                ('about_success', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='our_volunteers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volunteer_img', models.ImageField(upload_to='image_upload/event_image')),
                ('volunteer_name', models.CharField(max_length=100)),
                ('about_volunteer', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='trending_fundraisers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fundraiser_image', models.ImageField(upload_to='image_upload/fundraiser_image/')),
                ('fundraiser_name', models.CharField(max_length=50)),
                ('fundraise_by_name', models.CharField(max_length=50)),
                ('fundraise_by_image', models.ImageField(upload_to='image_upload/fundraise_by_image/')),
                ('fund_amout_raise', models.IntegerField()),
                ('fund_amount_target', models.IntegerField()),
                ('fund_start_date', models.DateField(null=True)),
                ('fund_end_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='what_people_say',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=50)),
                ('person_image', models.ImageField(upload_to='image_upload/what_people_say_image/')),
                ('person_review', models.TextField(max_length=500)),
            ],
        ),
    ]
