# Generated by Django 4.0.5 on 2022-07-30 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trending_fundraisers',
            name='fundraiser_support',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='our_volunteers',
            name='volunteer_facebook_id',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='our_volunteers',
            name='volunteer_instagrm_id',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='our_volunteers',
            name='volunteer_linkdin_id',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='our_volunteers',
            name='volunteer_twitter_id',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
