# Generated by Django 4.0.5 on 2022-07-26 11:23

from django.db import migrations, models
import home_app.models.incoming_event


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incoming_event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_img', models.ImageField(upload_to=home_app.models.incoming_event.Incoming_event.nameFile)),
                ('event_name', models.CharField(max_length=100)),
                ('event_location', models.CharField(max_length=300)),
                ('event_date', models.DateTimeField()),
            ],
        ),
    ]
