# Generated by Django 4.0.5 on 2022-07-26 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0002_incoming_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incoming_event',
            name='event_date',
            field=models.DateField(),
        ),
    ]
