# Generated by Django 4.0.5 on 2022-07-26 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0003_alter_incoming_event_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='our_volunteers',
            name='volunteer_facebook_id',
            field=models.URLField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='our_volunteers',
            name='volunteer_instagrm_id',
            field=models.URLField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='our_volunteers',
            name='volunteer_linkdin_id',
            field=models.URLField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='our_volunteers',
            name='volunteer_twitter_id',
            field=models.URLField(max_length=300, null=True),
        ),
    ]
