# Generated by Django 4.0.5 on 2022-07-29 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Auth', '0002_remove_newuser_cpassword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='Phone',
        ),
        migrations.AddField(
            model_name='newuser',
            name='phone',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
