# Generated by Django 4.0.5 on 2022-06-06 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fundraisers_medical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=50)),
                ('relation', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('target_amount', models.IntegerField()),
                ('patient_age', models.IntegerField()),
                ('patient_photo', models.ImageField(upload_to='uploads/patient_photo/')),
                ('medical_ailment', models.CharField(max_length=50)),
                ('current_situation_details', models.CharField(max_length=500)),
                ('hospital_name', models.CharField(max_length=50)),
                ('hospital_address', models.CharField(max_length=250)),
                ('patient_address', models.CharField(max_length=250)),
                ('doctor_name', models.CharField(max_length=50)),
                ('fundraiser_title', models.CharField(max_length=50)),
                ('fundraiser_description', models.CharField(max_length=600)),
                ('medical_documents', models.ImageField(upload_to='uploads/medical_document/')),
            ],
        ),
    ]
