# Generated by Django 4.0.5 on 2022-07-06 13:39

from django.db import migrations, models
import fundraisers.models.fundraisers_medical


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fundraisers_medical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=50)),
                ('benificiary', models.CharField(max_length=50)),
                ('relation', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('target_amount', models.IntegerField()),
                ('current_amount_raised', models.IntegerField()),
                ('end_date', models.DateField()),
                ('patient_age', models.IntegerField()),
                ('patient_photo', models.ImageField(upload_to=fundraisers.models.fundraisers_medical.Fundraisers_medical.nameFile)),
                ('medical_ailment', models.CharField(max_length=50)),
                ('current_situation_details', models.CharField(max_length=500)),
                ('hospital_name', models.CharField(max_length=50)),
                ('hospital_address', models.CharField(max_length=250)),
                ('patient_address', models.CharField(max_length=250)),
                ('doctor_name', models.CharField(max_length=50)),
                ('fundraiser_title', models.CharField(max_length=50)),
                ('fundraiser_description', models.CharField(max_length=600)),
                ('medical_documents', models.ImageField(upload_to=fundraisers.models.fundraisers_medical.Fundraisers_medical.nameFile)),
            ],
        ),
        migrations.CreateModel(
            name='ngo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regulation_certificate', models.ImageField(null=True, upload_to='uploads/ngo_proofs/regulation_certificate')),
                ('certificate_12A', models.ImageField(null=True, upload_to='uploads/ngo_proofs/certificate_12A')),
                ('valid_status', models.BooleanField(default=False)),
                ('type_of_ngo_certificate', models.TextField(max_length=50)),
                ('license_number', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('videos', models.FileField(blank=True, null=True, upload_to='uploads/ngo_proofs/ngo_videos')),
                ('description', models.TextField(max_length=200)),
                ('photo1', models.ImageField(blank=True, null=True, upload_to='uploads/ngo_proofs/ngo_photos')),
                ('photo2', models.ImageField(blank=True, null=True, upload_to='uploads/ngo_proofs/ngo_photos')),
                ('photo3', models.ImageField(blank=True, null=True, upload_to='uploads/ngo_proofs/ngo_photos')),
                ('photo4', models.ImageField(blank=True, null=True, upload_to='uploads/ngo_proofs/ngo_photos')),
                ('photo5', models.ImageField(blank=True, null=True, upload_to='uploads/ngo_proofs/ngo_photos')),
                ('address', models.CharField(max_length=200)),
                ('contact', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('media_links', models.URLField(blank=True)),
                ('created', models.CharField(max_length=100)),
                ('updated', models.CharField(max_length=100)),
            ],
        ),
    ]
