# Generated by Django 4.0.5 on 2022-06-18 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraisers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ngo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regulation_certificate', models.ImageField(null=True, upload_to='uploads/ngo_proofs/regulation_certificate')),
                ('certificate_12A', models.ImageField(null=True, upload_to='uploads/ngo_proofs/certificate_12A')),
                ('valid_status', models.BooleanField(default=False)),
                ('type_of_ngo_certificate', models.TextField(max_length=50)),
                ('license_number', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('videos', models.FileField(blank=True, null=True, upload_to='uploads/ngo_proofs/ngo_videos')),
                ('description', models.TextField(max_length=200)),
                ('photo1', models.ImageField(blank=True, null=True, upload_to='uploads/ngo_proofs/ngo_photos')),
                ('photo2', models.ImageField(blank=True, null=True, upload_to='uploads/ngo_proofs/ngo_photos')),
                ('photo3', models.ImageField(blank=True, null=True, upload_to='uploads/ngo_proofs/ngo_photos')),
                ('photo4', models.ImageField(blank=True, null=True, upload_to='uploads/ngo_proofs/ngo_photos')),
                ('photo5', models.ImageField(blank=True, null=True, upload_to='uploads/ngo_proofs/ngo_photos')),
                ('address', models.CharField(max_length=200)),
                ('contact', models.IntegerField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('media_links', models.URLField(blank=True)),
                ('created', models.CharField(max_length=100)),
                ('updated', models.CharField(max_length=100)),
            ],
        ),
    ]
