# Generated by Django 4.0.5 on 2022-06-19 07:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraisers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundraisers_medical',
            name='benificiary',
            field=models.CharField(default='aaaaa', max_length=50),
        ),
        migrations.AddField(
            model_name='fundraisers_medical',
            name='end_date',
            field=models.DateField(default=datetime.date(2022, 6, 19)),
        ),
    ]
