# Generated by Django 4.0.5 on 2022-06-19 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraisers', '0002_fundraisers_medical_benificiary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundraisers_medical',
            name='benificiary',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='fundraisers_medical',
            name='end_date',
            field=models.DateField(),
        ),
    ]
