# Generated by Django 4.0.5 on 2022-07-03 06:00

from django.db import migrations, models
import fundraisers.models.fundraisers_medical


class Migration(migrations.Migration):

    dependencies = [
        ('fundraisers', '0003_alter_fundraisers_medical_benificiary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundraisers_medical',
            name='current_amount_raised',
            field=models.IntegerField(default=50000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fundraisers_medical',
            name='medical_documents',
            field=models.ImageField(upload_to=fundraisers.models.fundraisers_medical.Fundraisers_medical.nameFile),
        ),
        migrations.AlterField(
            model_name='fundraisers_medical',
            name='patient_photo',
            field=models.ImageField(upload_to=fundraisers.models.fundraisers_medical.Fundraisers_medical.nameFile),
        ),
    ]
